version: "3.9"
services:
  mysql:
    image: 'mysql:8.0.30'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: catalogue_service
    ports:
      - "3306:3306"
